'''
This script uses shapefiles generated by running qgis_allDC.py in the
python terminal of qgis.

This will generate a python figure map of Washington DC containing only roads
and the District, Ward boundaries.
'''

from mpl_toolkits.basemap import Basemap
from mpl_toolkits.basemap import Basemap
import matplotlib.pyplot as plt
from matplotlib.patches import Polygon
from matplotlib.collections import PatchCollection
from matplotlib.patches import PathPatch
import numpy as np
import os

exec(open("./plot_shape.py").read())

# setup Lambert Conformal basemap.
# set resolution=None to skip processing of boundary datasets.
fig = plt.figure()

ax = fig.add_subplot(111)

map = Basemap(resolution= 'f',projection= 'lcc', epsg= 4326,llcrnrlon=-77.1203,
              llcrnrlat= 38.8538, urcrnrlon=-76.9114, urcrnrlat=38.9966,
              lat_0= 38.9248, lon_0= -77.0206)
map.drawcoastlines()
map.drawmapboundary(fill_color='black')
map.fillcontinents(color='white', lake_color='blue')

os.chdir((r"/media/j/TOSHIBA1/OneDrive - University of South Carolina - "
          r"Moore School of Business/CompEcon_Fall17/Problem Sets/Problem Set "
          r"5/ALL_DC_shapefiles"))

files = [s for s in os.listdir(os.getcwd()) if ".shp" in s]

for el in files:
    map.readshapefile(el[:-4], el[:-4])



plot_shape(map.water_info, map.water, 'blue', 'black', .1, 2, 1)

plot_shape(map.Ward_from_2012_info, map.Ward_from_2012, 'none', 'black', 1, 2, 1)


plt.show()

plt.savefig('allDC.png')
